// src/lib/playersDemo1.js
export const playersData = [
  { id: 1,  name: "Alberto",   info: { country: "Spain",     age: 34, profession: "Architect",        favoriteColor: "teal"   } },
  { id: 2,  name: "Beatriz",   info: { country: "Japan",     age: 27, profession: "Graphic Designer", favoriteColor: "magenta"} },
  { id: 3,  name: "Carmen",    info: { country: "Kenya",     age: 22, profession: "Teacher",          favoriteColor: "yellow" } },
  { id: 4,  name: "Diego",     info: { country: "Brazil",    age: 45, profession: "Software Engineer",favoriteColor: "blue"   } },
  { id: 5,  name: "Ernesto",   info: { country: "Canada",    age: 52, profession: "Chef",             favoriteColor: "green"  } },
  { id: 6,  name: "Fernando",  info: { country: "Mexico",    age: 30, profession: "Musician",         favoriteColor: "purple" } },
  { id: 7,  name: "Gabriela",  info: { country: "Germany",   age: 29, profession: "Journalist",       favoriteColor: "orange" } },
  { id: 8,  name: "Hernán",    info: { country: "Argentina", age: 41, profession: "Photographer",     favoriteColor: "red"    } },
  { id: 9,  name: "Isabella",  info: { country: "Italy",     age: 24, profession: "Doctor",           favoriteColor: "navy"   } },
  { id: 10, name: "Javier",    info: { country: "Australia", age: 38, profession: "Pilot",            favoriteColor: "sky"    } },
  { id: 11, name: "Karen",     info: { country: "India",     age: 50, profession: "Entrepreneur",     favoriteColor: "maroon" } },
  { id: 12, name: "Luis",      info: { country: "USA",       age: 33, profession: "Architect",        favoriteColor: "cyan"   } },
  { id: 13, name: "Mariana",   info: { country: "Portugal",  age: 26, profession: "Writer",           favoriteColor: "olive"  } },
  { id: 14, name: "Nicolás",   info: { country: "Sweden",    age: 47, profession: "Researcher",       favoriteColor: "lime"   } },
  { id: 15, name: "Olga",      info: { country: "Russia",    age: 58, profession: "Professor",        favoriteColor: "brown"  } },
  { id: 16, name: "Pedro",     info: { country: "Chile",     age: 21, profession: "Student",          favoriteColor: "pink"   } },
  { id: 17, name: "Quentin",   info: { country: "France",    age: 36, profession: "Designer",         favoriteColor: "coral"  } },
  { id: 18, name: "Rosa",      info: { country: "Morocco",   age: 31, profession: "Biologist",        favoriteColor: "emerald"} },
  { id: 19, name: "Santiago",  info: { country: "Peru",      age: 28, profession: "Developer",        favoriteColor: "amber"  } },
  { id: 20, name: "Teresa",    info: { country: "Portugal",  age: 42, profession: "Lawyer",           favoriteColor: "violet" } },
  { id: 21, name: "Ulises",    info: { country: "Greece",    age: 39, profession: "Historian",        favoriteColor: "navy"   } },
  { id: 22, name: "Valeria",   info: { country: "Colombia",  age: 25, profession: "Photographer",     favoriteColor: "teal"   } },
  { id: 23, name: "Walter",    info: { country: "USA",       age: 53, profession: "Engineer",         favoriteColor: "gray"   } },
  { id: 24, name: "Ximena",    info: { country: "Mexico",    age: 29, profession: "Nurse",            favoriteColor: "rose"   } },
  { id: 25, name: "Yahir",     info: { country: "El Salvador", age: 34,profession: "Musician",         favoriteColor: "indigo" } },
  { id: 26, name: "Zoila",     info: { country: "Dominican Rep.", age: 46,profession: "Chef",           favoriteColor: "slate"  } },
  { id: 27, name: "Amelia",    info: { country: "UK",        age: 27, profession: "Writer",           favoriteColor: "lavender"} },
  { id: 28, name: "Bruno",     info: { country: "Italy",     age: 44, profession: "Artist",           favoriteColor: "marigold"} },
  { id: 29, name: "Carlos",    info: { country: "Spain",     age: 32, profession: "Architect",        favoriteColor: "cerulean"} },
  { id: 30, name: "Daniel",    info: { country: "Canada",    age: 38, profession: "Teacher",          favoriteColor: "emerald"} },
  { id: 31, name: "Elena",     info: { country: "Russia",    age: 41, profession: "Engineer",         favoriteColor: "jade"   } },
  { id: 32, name: "Federico",  info: { country: "Argentina", age: 29, profession: "Journalist",       favoriteColor: "sunset" } }
];
